id: P006824
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ2485
  title: ཕྱག་ཆེན་ལྷན་ཅིག་སྐྱེས་སྦྱོར་ཟབ་དོན་ལམ་གྱི་སྙིང་པོ་གྲུབ་ཐོབ་བརྒྱུད་པའི་ཞལ་ལུང་
  author: ''
  volumes:
    97c8171bac31423db59592d0c9fbf129:
      image_group_id: I1CZ2495
      title: ''
      volume_number: 1
      total_pages: 534
      base_file: v001.txt
